
server.port=${SERVER_PORT:9000}

spring.datasource.url=${MYSQL_URL:jdbc:mysql://emartdb:3306/books?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto=update

