#!/usr/bin/env bash
# =============================================================================
# E-MART – Vault Sync Script
# =============================================================================
# Fetches secrets from HashiCorp Vault and writes them to .env in the
# repository root so that Docker Compose and local tooling can consume them.
#
# Supports two authentication methods:
#   1. Token auth   – set VAULT_TOKEN (dev / bootstrap only)
#   2. AppRole auth – set VAULT_ROLE_ID + VAULT_SECRET_ID (recommended)
#
# Usage:
#   # Token auth (dev)
#   VAULT_TOKEN=<token> ./scripts/vault-sync.sh
#
#   # AppRole auth
#   VAULT_ROLE_ID=<role-id> VAULT_SECRET_ID=<secret-id> ./scripts/vault-sync.sh
#
# The generated .env file is gitignored and should never be committed.
# =============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"
VAULT_ADDR="${VAULT_ADDR:-https://127.0.0.1:8200}"
VAULT_SKIP_VERIFY="${VAULT_SKIP_VERIFY:-false}"

export VAULT_ADDR

if [[ "${VAULT_SKIP_VERIFY}" == "true" ]]; then
  export VAULT_SKIP_VERIFY=true
fi

# ---------------------------------------------------------------------------
# Authenticate and obtain a client token
# ---------------------------------------------------------------------------
if [[ -n "${VAULT_TOKEN:-}" ]]; then
  echo "→ Using provided VAULT_TOKEN"
elif [[ -n "${VAULT_ROLE_ID:-}" && -n "${VAULT_SECRET_ID:-}" ]]; then
  echo "→ Authenticating via AppRole ..."
  VAULT_TOKEN=$(vault write -field=token auth/approle/login \
    role_id="${VAULT_ROLE_ID}" \
    secret_id="${VAULT_SECRET_ID}")
  export VAULT_TOKEN
else
  echo "ERROR: Set VAULT_TOKEN or both VAULT_ROLE_ID and VAULT_SECRET_ID"
  exit 1
fi

# ---------------------------------------------------------------------------
# Helper: fetch a Vault KV v2 secret field
# ---------------------------------------------------------------------------
vault_get() {
  local path="$1"
  local field="$2"
  vault kv get -field="${field}" "secret/${path}" 2>/dev/null || echo ""
}

echo "→ Reading secrets from Vault ..."

MONGO_URI=$(vault_get emartapp/nodeapi MONGO_URI)
JWT_SECRET=$(vault_get emartapp/nodeapi JWT_SECRET)
ADMIN_EMAILS=$(vault_get emartapp/nodeapi ADMIN_EMAILS)
SMTP_ENABLED=$(vault_get emartapp/nodeapi SMTP_ENABLED)
SMTP_SERVICE=$(vault_get emartapp/nodeapi SMTP_SERVICE)
SMTP_HOST=$(vault_get emartapp/nodeapi SMTP_HOST)
SMTP_USER=$(vault_get emartapp/nodeapi SMTP_USER)
SMTP_PASS=$(vault_get emartapp/nodeapi SMTP_PASS)

MYSQL_URL=$(vault_get emartapp/javaapi MYSQL_URL)
MYSQL_USER=$(vault_get emartapp/javaapi MYSQL_USER)
MYSQL_PASSWORD=$(vault_get emartapp/javaapi MYSQL_PASSWORD)

GRAFANA_ADMIN_USER=$(vault_get emartapp/observability GRAFANA_ADMIN_USER)
GRAFANA_ADMIN_PASSWORD=$(vault_get emartapp/observability GRAFANA_ADMIN_PASSWORD)

# ---------------------------------------------------------------------------
# Write .env (overwrite every run so it stays current)
# ---------------------------------------------------------------------------
echo "→ Writing ${ENV_FILE} ..."
cat > "${ENV_FILE}" <<EOF
# Generated by scripts/vault-sync.sh – DO NOT EDIT MANUALLY
# Re-run vault-sync.sh to refresh.

MONGO_URI=${MONGO_URI}
JWT_SECRET=${JWT_SECRET}
ADMIN_EMAILS=${ADMIN_EMAILS}
SMTP_ENABLED=${SMTP_ENABLED:-false}
SMTP_SERVICE=${SMTP_SERVICE}
SMTP_HOST=${SMTP_HOST}
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}

MYSQL_URL=${MYSQL_URL}
MYSQL_USER=${MYSQL_USER}
MYSQL_PASSWORD=${MYSQL_PASSWORD}
MYSQL_DATABASE=books

NGINX_PORT=80
API_PORT=5000
WEBAPI_PORT=9000
MONGO_INITDB_DATABASE=epoc

GRAFANA_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

VAULT_ADDR=${VAULT_ADDR}
VAULT_SKIP_VERIFY=${VAULT_SKIP_VERIFY:-false}
EOF

chmod 600 "${ENV_FILE}"
echo "✓ .env written (mode 600). Ready for: docker compose up"
